### ISSUE TITLE
Fix TYPO in namespace declaration

### ISSUE THREAD

**Issue by tobiasquadflieg** [Fanor51/headless-container-support#20]
The namespace should be 
`Fanor51\\HeadlessContainerSupport\\` 
instead of 
`Fanor51\\HeadlesContainerSupport\\`

https://github.com/TYPO3-Headless/headless-container-support/blob/bbd08c6e3b0d9120f329447f06af1b0a6fa4013a/composer.json#L26

**Comment by Fanor51** [comment]
Oh Damn, i didn´t notice this all the time.. Yes of course i will change this.

Thank you!

**Comment by Fanor51** [comment]
Hello @tobiasquadflieg ,

it´s changed in version 2.0.0

Best Regards
Fabio
